name: fossa
on:
  repository_dispatch:
    types: [fossa]
  push:
    branches:
      - master
      - release-*
      - feature/*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*
      - feature/*
  workflow_dispatch: {}
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: b88e1f4287c3108c8751bf106fb46db6 # This is a PUSH ONLY token that is safe to be shared with the public