name: Node.js CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VER: 14.17.6
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VER }}
      
    - name: Publish to npm
      if: env.DEPLOY_PACKAGE == 'true'
      run: ./scripts/publish.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
